export const MOCK_CATEGORIES = [
  { id: '1', name: 'Rice Dishes', slug: 'rice' },
  { id: '2', name: 'Swallow', slug: 'swallow' },
  { id: '3', name: 'Grills & BBQ', slug: 'grill' },
  { id: '4', name: 'Snacks & Small Chops', slug: 'snacks' },
  { id: '5', name: 'Cold Drinks', slug: 'drinks' },
  { id: '6', name: 'Soups', slug: 'soups' },
];

export const MOCK_ITEMS = [
  // ───────── Rice Dishes ─────────
  {
    id: '101',
    category_slug: 'rice',
    slug: 'party-jollof-rice',
    name: 'Party Jollof Rice (Classic)',
    description: 'Our award-winning smoky party jollof rice, slow-cooked over firewood for that authentic, charcoal-infused aroma. Served with perfectly caramelized fried plantains, a portion of creamy coleslaw, and grilled chicken. The definitive taste of a Nigerian celebration.',
    price: 3500,
    compare_price: 3800,
    preparation_time: 25,
    spice_level: 3,
    serves: '1 person',
    calories: '620 kcal',
    ingredients: ['Long grain rice', 'Tomato blend', 'Scotch bonnet pepper', 'Onions', 'Fried plantains', 'Grilled Chicken'],
    dietary_tags: ['spicy', 'popular', 'featured'],
    image_url: '/images/menu/jollof-rice-party.png',
    is_featured: true,
  },
  {
    id: '105',
    category_slug: 'rice',
    slug: 'fried-rice-chicken',
    name: 'Exotic Fried Rice & Grilled Chicken',
    description: 'Fluffy Nigerian-style fried rice tossed with sweet corn, carrots, green peas, and diced liver. Seasoned with premium curry and thyme, and served with a juicy quarter grilled chicken marinated in house spices.',
    price: 4000,
    preparation_time: 30,
    spice_level: 1,
    serves: '1 person',
    calories: '750 kcal',
    ingredients: ['Long grain rice', 'Mixed vegetables', 'Liver chunks', 'Grilled chicken', 'Seasoning'],
    dietary_tags: ['popular'],
    image_url: '/images/menu/jollof-rice-party.png',
  },
  {
    id: '108',
    category_slug: 'rice',
    slug: 'coconut-rice-fried-fish',
    name: 'Creamy Coconut Rice & Fried Croaker',
    description: 'Aromatic rice infused with fresh coconut milk, garlic, and ginger. Served with a whole large fried Croaker fish seasoned with local herbs. A rich and satisfying coastal delicacy.',
    price: 4500,
    preparation_time: 35,
    spice_level: 1,
    serves: '1 person',
    calories: '810 kcal',
    ingredients: ['Long grain rice', 'Fresh coconut milk', 'Croaker fish', 'Garlic', 'Ginger'],
    dietary_tags: ['seafood'],
    image_url: '/images/menu/jollof-rice-party.png',
  },

  // ───────── Swallows & Soups ─────────
  {
    id: '102',
    category_slug: 'swallow',
    slug: 'pounded-yam-egusi',
    name: 'Pounded Yam & Special Egusi',
    description: 'Smooth, stretchy pounded yam paired with our rich Lumpy Egusi soup. The soup is slow-cooked with palm oil, ground melon seeds, spinach, and a generous mix of assorted meat, stockfish, and dried fish. Pure comfort on a plate.',
    price: 4200,
    compare_price: 4500,
    preparation_time: 30,
    spice_level: 2,
    serves: '1 person',
    calories: '820 kcal',
    ingredients: ['Pounded yam', 'Egusi seeds', 'Assorted meat', 'Stockfish', 'Spinach', 'Palm oil'],
    dietary_tags: ['popular', 'featured'],
    image_url: '/images/menu/egusi-pounded-yam.png',
    is_featured: true,
  },
  {
    id: '106',
    category_slug: 'swallow',
    slug: 'amala-ewedu-gbegiri',
    name: 'Amala, Ewedu & Gbegiri (Lagos Special)',
    description: 'Authentic dark yam flour (Amala) served with silky Ewedu leaf soup and creamy Gbegiri (bean soup), topped with spicy pepper stew and assorted meat. The ultimate Yoruba classic experience.',
    price: 3800,
    preparation_time: 20,
    spice_level: 3,
    serves: '1 person',
    calories: '780 kcal',
    ingredients: ['Yam flour', 'Jute leaves (Ewedu)', 'Honey beans', 'Assorted beef', 'Palm oil'],
    dietary_tags: ['popular', 'traditional'],
    image_url: '/images/menu/egusi-pounded-yam.png',
  },
  {
    id: '109',
    category_slug: 'swallow',
    slug: 'eba-ogbono-soup',
    name: 'Eba & Fishermans Ogbono Soup',
    description: 'Golden Eba (garri) alongside a thick, drawing Ogbono soup made from wild bush mango seeds. Features tender goat meat, kpomo, and fresh pumpkin leaves (Ugu), enriched with ground crayfish.',
    price: 3500,
    preparation_time: 25,
    spice_level: 2,
    serves: '1 person',
    calories: '790 kcal',
    ingredients: ['Cassava flakes (Garri)', 'Ogbono seeds', 'Goat meat', 'Kpomo', 'Crayfish'],
    dietary_tags: ['filling'],
    image_url: '/images/menu/egusi-pounded-yam.png',
  },

  // ───────── Grills & BBQ ─────────
  {
    id: '103',
    category_slug: 'grill',
    slug: 'catfish-pepper-soup',
    name: 'Point-and-Kill Catfish Pepper Soup',
    description: 'Fiery and aromatic catfish pepper soup prepared with fresh whole catfish. Our secret blend of Ehuru, Uziza, and Scent leaves creates a broth that is both medicinal and intensely satisfying.',
    price: 5500,
    preparation_time: 35,
    spice_level: 4,
    serves: '1 person',
    calories: '380 kcal',
    ingredients: ['Fresh catfish', 'Uziza seeds', 'Ehuru', 'Uda', 'Scent leaves', 'Chili'],
    dietary_tags: ['spicy', 'seafood'],
    image_url: '/images/menu/pepper-soup.jpg',
  },
  {
    id: '107',
    category_slug: 'grill',
    slug: 'spicy-asun',
    name: 'Smokey Goat Asun (Large)',
    description: 'Bite-sized chunks of tender goat meat, slow-grilled and sautéed in a fiery mix of scotch bonnet peppers and onions. Perfectly charred with a lingering smoky finish.',
    price: 6000,
    preparation_time: 40,
    spice_level: 5,
    serves: '2 people',
    calories: '450 kcal',
    ingredients: ['Goat meat', 'Red bell peppers', 'Onions', 'Habanero pepper', 'Local spices'],
    dietary_tags: ['spicy', 'popular'],
    image_url: '/images/brand/hero-bg.jpg',
  },
  {
    id: '110',
    category_slug: 'grill',
    slug: 'suya-beef-skewers',
    name: 'Beef Suya Platter',
    description: 'The definitive Nigerian street food. Thinly sliced beef marinated in spicy Yaji (groundnut-based rub) and smoked over open coals. Served with extra yaji, sliced onions, and tomatoes.',
    price: 3000,
    preparation_time: 15,
    spice_level: 3,
    serves: '1 person (4 sticks)',
    calories: '420 kcal',
    ingredients: ['Premium Beef', 'Yaji Spice', 'Groundnut oil', 'Onions', 'Tomatoes'],
    dietary_tags: ['spicy', 'popular'],
    image_url: '/images/brand/hero-bg.jpg',
  },

  // ───────── Snacks & Small Chops ─────────
  {
    id: '116',
    category_slug: 'snacks',
    slug: 'small-chops-platter',
    name: 'Executive Small Chops Platter',
    description: 'A curated selection of Nigerian party favorites: 4 Puff-Puff, 2 Samosas, 2 Spring Rolls, and 2 pieces of spicy gizzard. Served with our house-made spicy dipping sauce.',
    price: 2500,
    preparation_time: 15,
    spice_level: 2,
    serves: '1 person',
    calories: '450 kcal',
    ingredients: ['Puff-Puff', 'Spring Rolls', 'Samosas', 'Peppered Gizzard'],
    dietary_tags: ['popular', 'snack'],
    image_url: '/images/brand/hero-bg.jpg',
  },
  {
    id: '104',
    category_slug: 'snacks',
    slug: 'puff-puff',
    name: 'Soft & Fluffy Puff Puff (10pcs)',
    description: 'Deep-fried golden dough balls - soft, airy, and slightly sweet with a hint of nutmeg. These are fried fresh throughout the day to ensure maximum fluffiness.',
    price: 1500,
    preparation_time: 10,
    spice_level: 0,
    serves: '1 person (10 pieces)',
    calories: '320 kcal',
    ingredients: ['Flour', 'Sugar', 'Yeast', 'Nutmeg', 'Vegetable Oil'],
    dietary_tags: ['vegetarian'],
    image_url: '/images/brand/hero-bg.jpg',
  },
  {
    id: '112',
    category_slug: 'snacks',
    slug: 'meat-pie',
    name: 'Classic Nigerian Meat Pie',
    description: 'Flaky, buttery pastry filled with perfectly seasoned minced beef, carrots, and potatoes. Baked until golden brown. The ultimate midday snack.',
    price: 1000,
    preparation_time: 5,
    spice_level: 0,
    serves: '1 piece',
    calories: '350 kcal',
    ingredients: ['Shortcrust pastry', 'Minced beef', 'Diced potatoes', 'Carrots'],
    dietary_tags: ['favourite'],
    image_url: '/images/brand/hero-bg.jpg',
  },

  // ───────── Cold Drinks ─────────
  {
    id: '113',
    category_slug: 'drinks',
    slug: 'chapman',
    name: 'Signature Lagos Chapman',
    description: "Our signature mocktail. A refreshing blend of Fanta, Sprite, Ribena, and Angostura bitters. Garnished with cucumber slices and fresh lemon. served ice-cold.",
    price: 2500,
    preparation_time: 5,
    spice_level: 0,
    serves: '1 glass (500ml)',
    calories: '180 kcal',
    ingredients: ['Fanta', 'Sprite', 'Ribena', 'Bitters', 'Cucumber', 'Lemon'],
    dietary_tags: ['refreshing', 'non-alcoholic'],
    image_url: '/images/brand/hero-bg.jpg',
  },
  {
    id: '114',
    category_slug: 'drinks',
    slug: 'zobo-drink',
    name: 'Fresh Zobo (Hibiscus) Brew',
    description: 'Traditional hibiscus petal drink brewed with fresh ginger, pineapple chunks, and a hint of cloves. Naturally refreshing and rich in Vitamin C.',
    price: 1500,
    preparation_time: 5,
    spice_level: 1,
    serves: '500ml Bottle',
    calories: '120 kcal',
    ingredients: ['Hibiscus petals', 'Fresh Ginger', 'Pineapple coat', 'Cloves'],
    dietary_tags: ['healthy', 'organic'],
    image_url: '/images/brand/hero-bg.jpg',
  },
  {
    id: '115',
    category_slug: 'drinks',
    slug: 'kunun-aya',
    name: 'Fresh Kunun Aya (Tiger Nut Milk)',
    description: 'A creamy, dairy-free milk made from fresh tiger nuts and dates, with a hint of coconut. Lightly sweetened and served bone-chillingly cold.',
    price: 2000,
    preparation_time: 5,
    spice_level: 0,
    serves: '500ml Bottle',
    calories: '210 kcal',
    ingredients: ['Tiger nuts', 'Dates', 'Coconut milk', 'Water'],
    dietary_tags: ['dairy-free', 'vegan'],
    image_url: '/images/brand/hero-bg.jpg',
  },

  // ───────── Soups ─────────
  {
    id: '117',
    category_slug: 'soups',
    slug: 'afang-soup',
    name: 'Afang Soup',
    description: 'A delicious soup from the south south part in Nigeria made with waterleaf and afang leaf',
    price: 3000,
    preparation_time: 30,
    spice_level: 3,
    serves: '1 person',
    calories: '450 kcal',
    ingredients: ['Afang leaves', 'Waterleaf', 'Assorted meat', 'Periwinkles', 'Palm oil'],
    dietary_tags: ['traditional', 'south-south'],
    image_url: '/images/menu/afang-soup.png',
  },
  {
    id: '118',
    category_slug: 'soups',
    slug: 'egusi-soup',
    name: 'Egusi Soup',
    description: 'Rich, hearty Nigerian soup made from ground melon seeds cooked with palm oil, vegetables, creating a thick, flavorful base perfect for enjoying with swallow foods.',
    price: 2500,
    preparation_time: 25,
    spice_level: 2,
    serves: '1 person',
    calories: '520 kcal',
    ingredients: ['Egusi seeds', 'Palm oil', 'Spinach', 'Assorted meat', 'Crayfish'],
    dietary_tags: ['traditional', 'popular'],
    image_url: '/images/menu/egusi-soup.jpg',
  },
  {
    id: '119',
    category_slug: 'soups',
    slug: 'okra-soup',
    name: 'Okra Soup',
    description: 'Viscous, nutritious soup made from fresh okra, cooked with palm oil, and traditional spices, featuring a distinctive slippery texture ideal for swallowing',
    price: 2500,
    preparation_time: 20,
    spice_level: 2,
    serves: '1 person',
    calories: '410 kcal',
    ingredients: ['Fresh Okra', 'Palm oil', 'Fish', 'Meat', 'Traditional spices'],
    dietary_tags: ['traditional', 'nutritious'],
    image_url: '/images/menu/okra-soup.jpg',
  },
  {
    id: '120',
    category_slug: 'soups',
    slug: 'vegetable-soup',
    name: 'Vegetable Soup (Edikang Ikong Style)',
    description: 'Luxurious vegetable soup featuring a medley of waterleaf and ugu cooked with palm oil; a perfect balance of nutrition and flavor.',
    price: 2500,
    preparation_time: 30,
    spice_level: 2,
    serves: '1 person',
    calories: '480 kcal',
    ingredients: ['Waterleaf', 'Ugu (Pumpkin leaves)', 'Palm oil', 'Assorted meat', 'Crayfish'],
    dietary_tags: ['traditional', 'healthy'],
    image_url: '/images/menu/vegetable-soup.jpg',
  },
  {
    id: '121',
    category_slug: 'swallow',
    slug: 'oatmeal-swallow',
    name: 'Oatmeal Swallow',
    description: '100% unadulterated whole grain oats blended and cooked into a soft swallow. Rich in fiber, supports heart health, lowers cholesterol, contains antioxidants and aids weight management. Great for prediabetics and diabetics.',
    price: 1000,
    preparation_time: 15,
    spice_level: 0,
    serves: '1 person',
    calories: '280 kcal',
    ingredients: ['Whole grain oats', 'Water'],
    dietary_tags: ['healthy', 'diabetic-friendly', 'fiber-rich'],
    image_url: '/images/menu/oatmeal-swallow.png',
  },
  {
    id: '122',
    category_slug: 'swallow',
    slug: 'semo',
    name: 'Semo',
    description: 'Light-colored, smooth semolina swallow with a neutral taste and perfect elasticity, making it an ideal companion for richly flavored Nigerian soups.',
    price: 600,
    preparation_time: 15,
    spice_level: 0,
    serves: '1 person',
    calories: '360 kcal',
    ingredients: ['Semolina flour', 'Water'],
    dietary_tags: ['classic', 'filling'],
    image_url: '/images/menu/semo.png',
  },
];
